### ISSUE TITLE
German Game Transliton not Workin

### ISSUE THREAD

**Issue by JokreeTV** [tenshi64/DbD-Advanced-Settings-Changer#4]
Hello, i have set the Game Language to German and its every on Start DBD to English.
![image](https://github.com/tenshi64/DbD-Advanced-Settings-Changer/assets/57968904/9ebfc772-8db4-479a-b18d-01204b674995)

**Comment by tenshi64** [comment]
I will fix this bug in a future version! Thank you for reporting. Sorry for the long response time, but I haven't received any notification about this issue.
