### ISSUE TITLE
tria.ge detects this as ransomware

### ISSUE THREAD

**Issue by gayloo** [tenshi64/DbD-Advanced-Settings-Changer#8]
tria.ge uses real VM's to test if files are malicious, there wouldn't be any false positives

Setup.msi: https://tria.ge/240519-q4jc2sah9w/behavioral1
setup.exe: https://tria.ge/240519-q2wwcsah5x/behavioral1

**Comment by tenshi64** [comment]
You scanned a setup file which is provided by Microsoft, I am not aware of any viruses in the app itself.
